/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

public class App {


    public static void main(String[] args) throws IOException {

//        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
//        InputStream is = classloader.getResourceAsStream("quotes.json");

        Quot quot=gsonQuote(0,"quotes.json");
        System.out.println(quot);
        Quot quotExp=new Quot("Marilyn Monroe","I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.");



        System.out.println(quotExp);

    }


    public static Quot gsonQuote(int num,String filename) throws IOException {
        Gson gson=new Gson();
//        URL url=new URL("https://codefellows.github.io/code-401-java-guide/curriculum/class-08/recentquotes.json");
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream(filename);

        Reader reader1= new InputStreamReader(is);

//        Reader reader= new BufferedReader(new InputStreamReader(url.openStream()));
        List<Quot> quotList=gson.fromJson(reader1,new TypeToken<List<Quot>>() {}.getType());
//        Quot quot=gson.fromJson(reader,Quot.class);
//        System.out.println(quot+"///////");

        int random_int = (int)Math.floor(Math.random()*(quotList.size()+1));
//        System.out.println(quotList.get(random_int));

        reader1.close();

        return quotList.get(num) ;

    }
}
